import { z } from 'zod';
import { getChatGPTUser } from '@/app/chatgpt-auth';
import { database } from '@/db/store';
export const dynamic='force-dynamic';
const validDay=(day:unknown)=>typeof day==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(day)&&Number.isFinite(Date.parse(day))&&new Date(day).toISOString().slice(0,10)===day;
const entryInput=z.object({pillar:z.enum(['social','emotional','generative','purpose','integration']),title:z.string().trim().min(1).max(180),kind:z.enum(['exercise','action','review']),status:z.enum(['done','planned']),day:z.string().refine(validDay),data:z.record(z.string()).refine(data=>JSON.stringify(data).length<=16000)});
const actionInput=z.object({id:z.string().min(1),day:z.string().refine(validDay)});
const reply=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
export async function GET(){const user=await getChatGPTUser();if(!user)return reply({error:'Sign in to load your personal practice history.'},401);try {const result=await database().prepare('SELECT id,pillar,title,kind,status,day,data,created FROM entries WHERE user_id=? ORDER BY created DESC').bind(user.userId).all();return reply({entries:result.results.map((r:any)=>({...r,data:JSON.parse(r.data)}))});}catch(e){console.error(e);return reply({error:'Your history could not be loaded. Please try again.'},503);}}
export async function POST(req:Request){const user=await getChatGPTUser();if(!user)return reply({error:'Sign in to save your practice.'},401);if(req.headers.get('origin')&&req.headers.get('origin')!==new URL(req.url).origin)return reply({error:'Invalid origin'},403);try{const parsed=entryInput.safeParse(await req.json());if(!parsed.success)return reply({error:'Please check your entry.'},400);const b=parsed.data;const id=crypto.randomUUID(),created=new Date().toISOString();await database().prepare('INSERT INTO entries (id,user_id,pillar,title,kind,status,day,data,created) VALUES (?,?,?,?,?,?,?,?,?)').bind(id,user.userId,b.pillar,b.title,b.kind,b.status,b.day,JSON.stringify(b.data),created).run();return reply({entry:{...b,id,created}},201);}catch(e){console.error(e);return reply({error:'Your entry could not be saved. Your answers are still here; please try again.'},503);}}
export async function PATCH(req:Request){const user=await getChatGPTUser();if(!user)return reply({error:'Sign in to update an action.'},401);if(req.headers.get('origin')&&req.headers.get('origin')!==new URL(req.url).origin)return reply({error:'Invalid origin'},403);try{const parsed=actionInput.safeParse(await req.json());if(!parsed.success)return reply({error:'Invalid action'},400);const b=parsed.data;const result=await database().prepare("UPDATE entries SET status='done',day=? WHERE id=? AND user_id=? AND status='planned'").bind(b.day,b.id,user.userId).run();if(!result.meta.changes)return reply({error:'This action is no longer available. Refresh your history.'},404);return reply({ok:true});}catch(e){console.error(e);return reply({error:'Could not update your action. Please try again.'},503);}}
export async function DELETE(req:Request){const user=await getChatGPTUser();if(!user)return reply({error:'Sign in to delete an entry.'},401);if(req.headers.get('origin')&&req.headers.get('origin')!==new URL(req.url).origin)return reply({error:'Invalid origin'},403);try{const id=new URL(req.url).searchParams.get('id');if(!id)return reply({error:'Missing entry'},400);await database().prepare('DELETE FROM entries WHERE id=? AND user_id=?').bind(id,user.userId).run();return reply({ok:true});}catch(e){console.error(e);return reply({error:'Could not delete the entry.'},503);}}
