'use client';
import {useEffect,useState} from 'react';
import {Users,Wind,Sparkles,Compass,ArrowUpRight,ArrowLeft,Check,Plus,BookOpen,CalendarDays,BarChart3,Heart,Play,Pause,RotateCcw,LockKeyhole,Trash2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {pillars,exercises,Exercise} from './content';
type Entry={id:string;pillar:string;title:string;kind:string;status:string;day:string;data:Record<string,string>;created:string};
const icons=[Users,Wind,Sparkles,Compass];
function dateKey(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function dayLabel(s:string){return new Date(s+'T12:00:00').toLocaleDateString('en-GB',{day:'numeric',month:'short'});}
function daysBack(){return Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);return dateKey(d);});}
export default function Companion({signedIn}:{signedIn:boolean}){
const [tab,setTab]=useState('today'),[entries,setEntries]=useState<Entry[]>([]),[loading,setLoading]=useState(signedIn),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState<Exercise|null>(null),[filter,setFilter]=useState('all'),[answers,setAnswers]=useState<Record<string,string>>({}),[remove,setRemove]=useState<string|null>(null),[showAction,setShowAction]=useState(false),[action,setAction]=useState(''),[actionPillar,setActionPillar]=useState('social'),[actionDay,setActionDay]=useState(dateKey()),[when,setWhen]=useState('');
async function load(){if(!signedIn)return;setLoading(true);setError('');try{const r=await fetch('/api/entries');const j=await r.json();if(!r.ok)throw Error(j.error);setEntries(j.entries);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
useEffect(()=>{load();},[]);
async function save(payload:Partial<Entry>){setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/entries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok)throw Error(j.error);setEntries(e=>[j.entry,...e]);setNotice(payload.status==='planned'?'Your next action is saved.':'Saved to your personal history.');return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}}
async function complete(e:Entry){setBusy(true);setError('');try{const r=await fetch('/api/entries',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:e.id,day:dateKey()})});const j=await r.json();if(!r.ok)throw Error(j.error);setEntries(a=>a.map(x=>x.id===e.id?{...x,status:'done',day:dateKey()}:x));setNotice('Action recorded. Small steps count.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
async function deleteEntry(){if(!remove)return;setBusy(true);try{const r=await fetch('/api/entries?id='+encodeURIComponent(remove),{method:'DELETE'});const j=await r.json();if(!r.ok)throw Error(j.error);setEntries(a=>a.filter(x=>x.id!==remove));setNotice('Entry deleted.');setRemove(null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
function openExercise(e:Exercise){setSelected(e);setAnswers({});setTab('practice');setNotice('');setError('');window.scrollTo({top:0,behavior:'smooth'});}
const days=daysBack(),done=entries.filter(e=>e.status==='done'),recent=done.filter(e=>days.includes(e.day)),activeDays=new Set(recent.map(e=>e.day)).size,plans=entries.filter(e=>e.status==='planned');
const pillarName=(id:string)=>pillars.find(p=>p.id===id)?.name||'Across the pillars';
return <div className="app-shell"><header className="masthead"><a href="/" className="wordmark"><span className="brand-mark"><Heart size={23}/></span><span>Emotional Health<span className="wordmark-sub">FOR LONGEVITY</span></span></a><span className="personal-label"><LockKeyhole size={14}/> Your personal practice</span></header>
<Tabs value={tab} onValueChange={v=>{setTab(v);setNotice('');setError('');}}><div className="nav-wrap"><TabsList className="main-nav" aria-label="Main navigation"><TabsTrigger value="today"><CalendarDays/>My day</TabsTrigger><TabsTrigger value="framework"><BookOpen/>The framework</TabsTrigger><TabsTrigger value="practice"><Sparkles/>Exercises</TabsTrigger><TabsTrigger value="progress"><BarChart3/>My progress</TabsTrigger><TabsTrigger value="about"><Users/>About</TabsTrigger></TabsList><span className="nav-caption">life <b>·</b> health <b>·</b> soul</span></div>
<main>
{!signedIn&&<div className="sign-in-note"><LockKeyhole size={18}/><span>Explore freely. Sign in to save exercises and track your practice.</span><a href="/signin-with-chatgpt?return_to=/" target="_top">Sign in with ChatGPT <ArrowUpRight size={16}/></a></div>}
{error&&<div role="alert" className="message error">{error} {tab==='progress'||tab==='today'?<button onClick={load}>Retry loading</button>:null}</div>}{notice&&<div role="status" className="message success"><Check size={18}/>{notice}</div>}
<TabsContent value="today"><section className="day-heading"><div><p className="eyebrow">YOUR EVERYDAY PRACTICE</p><h1>A little attention.<br/><em>A meaningful difference.</em></h1><p className="intro">Choose one small action for your emotional health today.</p></div><div className="week-dial"><span className="dial-value">{loading?'—':activeDays}<small>/ 7</small></span><span>days with a practice</span><span className="muted">in the last week</span><div className="mini-days">{days.map(day=><span key={day} className={recent.some(e=>e.day===day)?'filled':''} title={dayLabel(day)}/>)}</div></div></section>
<div className="section-line"><h2>Where would you like to start?</h2><button onClick={()=>setTab('framework')}>Meet the four pillars <ArrowUpRight size={16}/></button></div>
<div className="pillar-grid">{pillars.map((p,i)=>{const Icon=icons[i];return <button className={'pillar-card p-'+p.id} key={p.id} onClick={()=>{setFilter(p.id);setSelected(null);setTab('practice');}}><div className="card-top"><span className="icon-tile"><Icon size={25}/></span><span className="number">{p.number}</span></div><h3>{p.name}</h3><p>{p.subtitle}</p><div className="card-bottom"><span>{exercises.filter(e=>e.pillar===p.id).length} practical exercises</span><ArrowUpRight size={20}/></div></button>;})}</div>
<div className="today-bottom"><section className="next-panel"><div className="section-line"><h2>My next small action</h2><Button variant="ghost" onClick={()=>setShowAction(!showAction)}><Plus size={18}/>{showAction?'Close':'Add action'}</Button></div>{plans.length===0&&!showAction&&<div className="empty-action"><Compass size={28}/><p>Something small enough for a normal day.</p><span>Call a friend. Pause before replying. Pick up a hobby.</span><Button onClick={()=>setShowAction(true)}>Choose my one thing <Plus size={16}/></Button></div>}{plans.map(e=><div className="plan" key={e.id}><div><span className="eyebrow">{pillarName(e.pillar)}</span><h3>{e.title}</h3><p>{dayLabel(e.day)}{e.data.when?' · '+e.data.when:''}</p></div><Button variant="outline" disabled={busy} onClick={()=>complete(e)}><Check/>Done</Button></div>)}
{showAction&&<form className="action-form" onSubmit={async e=>{e.preventDefault();if(await save({title:action.trim(),pillar:actionPillar,kind:'action',status:'planned',day:actionDay,data:{when}})){setAction('');setWhen('');setShowAction(false);}}}><label htmlFor="action">My small action</label><Input id="action" required maxLength={180} value={action} onChange={e=>setAction(e.target.value)} placeholder="Call a friend on my lunch break"/><div className="form-row"><div><label htmlFor="pillar">Pillar</label><Select value={actionPillar} onValueChange={setActionPillar}><SelectTrigger id="pillar"><SelectValue/></SelectTrigger><SelectContent>{pillars.map(p=><SelectItem key={p.id} value={p.id}>{p.name}</SelectItem>)}</SelectContent></Select></div><div><label htmlFor="day">Day</label><Input id="day" type="date" required value={actionDay} onChange={e=>setActionDay(e.target.value)}/></div></div><label htmlFor="when">When or where? <small>Optional</small></label><Input id="when" maxLength={500} value={when} onChange={e=>setWhen(e.target.value)} placeholder="After lunch, before the afternoon starts"/><Button type="submit" disabled={busy||!signedIn||!action.trim()}>{busy?'Saving…':'Save my action'}</Button></form>}</section><aside className="pause-card"><span className="eyebrow">A MOMENT TO RESET</span><div className="pause-symbol"><Wind size={42}/></div><h2>Notice. Pause. Choose.</h2><p>A gentle breathing exercise to make a little space before your next step.</p><Button onClick={()=>openExercise(exercises.find(e=>e.id==='breathing')!)}>Take a one-minute pause <ArrowUpRight size={17}/></Button><span className="small">Comfortable breathing. Your own pace.</span></aside></div>
<section className="integration-strip"><span className="connection-symbol">4<span>→</span>1</span><div><h2>One activity can touch all four pillars.</h2><p>Learning a song with friends brings connection, patience, creativity and a shared purpose.</p></div><Button variant="outline" onClick={()=>openExercise(exercises.find(e=>e.id==='integration')!)}>Connect the pillars <ArrowUpRight/></Button></section></TabsContent>
<TabsContent value="framework"><div className="page-title"><p className="eyebrow">UNDERSTAND THE FRAMEWORK</p><h1>Living longer.<br/><em>Living more fully.</em></h1><p className="intro">Emotional health deserves everyday attention, alongside physical health.</p></div><div className="three-spans">{[['Lifespan','How long you live','The length of your life.'],['Healthspan','How well you live','The years spent in good health.'],['Soulspan','How deeply you live','Purpose, connection and meaning. A reflection concept used in this framework, not a clinical measure.']].map(x=><div key={x[0]}><span className="eyebrow">{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div>
<div className="framework-list">{pillars.map((p,i)=>{const Icon=icons[i];return <section key={p.id} className="framework-pillar"><div className="pillar-label"><span>{p.number}</span><Icon size={30}/><h2>{p.name}</h2><p>{p.subtitle}</p></div><div><p className="lead">{p.description}</p><p>{p.why}</p><blockquote>{p.example}</blockquote><details><summary>What the evidence can and cannot tell us</summary><p>{p.evidence}</p></details><Button onClick={()=>{setFilter(p.id);setSelected(null);setTab('practice');}}>Try a {p.short.toLowerCase()} exercise <ArrowUpRight size={16}/></Button></div></section>;})}</div><section className="reading"><h2>A practical framework, not a score</h2><p>The four pillars overlap. You do not need to practise every pillar every day, and a logged action is not a measure of mental health or a promise of longer life. Use the tracker to discover what is useful to you.</p><details><summary>Sources and further reading</summary><p>Adapted from the Emotional Health for Longevity presentation and participant workbook.</p><ul><li>Holt-Lunstad, Smith & Layton (2010), Social relationships and mortality risk, PLoS Medicine 7(7), e1000316.</li><li>WHO (2025), From loneliness to social connection.</li><li>Cené et al. (2022), Social isolation and loneliness as risk factors for cardiovascular and brain health, JAHA 11, e026493.</li><li>Harvard Study of Adult Development; Waldinger & Schulz (2023), The Good Life.</li><li>Lieberman et al. (2007), Putting feelings into words, Psychological Science 18, 421–428.</li><li>Su et al. (2022), Leisure activities and the risk of dementia, Neurology 99, e1651–e1663.</li><li>Ryan & Deci (2000), Self-determination theory, American Psychologist 55, 68–78.</li><li>Frankl, Man’s Search for Meaning; Csikszentmihalyi (1990), Flow.</li></ul></details></section></TabsContent>
<TabsContent value="practice">{selected?<section className="exercise-workspace"><Button variant="ghost" onClick={()=>setSelected(null)}><ArrowLeft/>All exercises</Button><div className="exercise-layout"><aside><span className="eyebrow">{pillarName(selected.pillar)} · {selected.minutes} MIN</span><h1>{selected.title}</h1><p>{selected.intro}</p><div className="gentle-note"><Sparkles size={20}/><p>{selected.hint}</p></div><span className="privacy"><LockKeyhole size={16}/>Your saved responses belong to your signed-in account. Use initials and leave out details you do not want to store.</span></aside><form className="exercise-form" onSubmit={async e=>{e.preventDefault();const data=Object.fromEntries(selected.prompts.map((q,i)=>[q,answers[i]||'']));if(await save({title:selected.title,pillar:selected.pillar,kind:selected.id==='review'?'review':'exercise',status:'done',day:dateKey(),data})){setSelected(null);setAnswers({});}}}>{selected.breathing&&<Breathing/>}{selected.chips&&<div className="emotion-words"><span>Find a starting word</span><div>{selected.chips.map(w=><button type="button" className={answers[1]===w?'chosen':''} key={w} onClick={()=>setAnswers({...answers,1:w})}>{w}</button>)}</div></div>}{selected.prompts.map((q,i)=><div className="question" key={q}><label htmlFor={'q'+i}><span>{String(i+1).padStart(2,'0')}</span>{q}</label><Textarea id={'q'+i} value={answers[i]||''} maxLength={2000} onChange={e=>setAnswers({...answers,[i]:e.target.value})} placeholder="A few words are enough…"/></div>)}<div className="form-bottom"><p>You can skip a prompt. Save at least one response.</p><Button type="submit" disabled={!signedIn||busy||!Object.values(answers).some(v=>v.trim())}>{busy?'Saving…':'Save reflection'}<Check size={18}/></Button></div></form></div></section>:<><div className="page-title"><p className="eyebrow">PUT IT INTO PRACTICE</p><h1>Make space for <em>you.</em></h1><p className="intro">Short, guided exercises for an ordinary day. Choose what feels useful.</p></div><div className="filter-row" aria-label="Filter exercises"><Button variant={filter==='all'?'default':'outline'} onClick={()=>setFilter('all')}>All exercises</Button>{pillars.map(p=><Button key={p.id} variant={filter===p.id?'default':'outline'} onClick={()=>setFilter(p.id)}>{p.name}</Button>)}<Button variant={filter==='integration'?'default':'outline'} onClick={()=>setFilter('integration')}>Bring it together</Button></div><div className="exercise-grid">{exercises.filter(e=>filter==='all'||e.pillar===filter).map(e=><button className="exercise-card" key={e.id} onClick={()=>openExercise(e)}><span className="eyebrow">{pillarName(e.pillar)}</span><h2>{e.title}</h2><p>{e.intro}</p><div><span>{e.minutes} min · {e.breathing?'Guided breathing':'Guided reflection'}</span><ArrowUpRight size={22}/></div></button>)}</div></>}</TabsContent>
<TabsContent value="progress"><div className="page-title progress-title"><div><p className="eyebrow">YOUR PERSONAL HISTORY</p><h1>Notice what <em>helps.</em></h1><p className="intro">Small actions, honest reflections. No perfect weeks required.</p></div><Button onClick={()=>openExercise(exercises.find(e=>e.id==='review')!)}>Reflect on my week <ArrowUpRight/></Button></div>{loading?<p className="loading">Loading your practice history…</p>:<><div className="stats-row"><div><strong>{activeDays}<small>/7</small></strong><span>days practised this week</span></div><div><strong>{recent.length}</strong><span>actions and exercises this week</span></div><div><strong>{new Set(recent.flatMap(e=>e.pillar==='integration'?[]:[e.pillar])).size}<small>/4</small></strong><span>individual pillars explored</span></div></div><section className="week-panel"><div className="section-line"><h2>Your last seven days</h2><span className="muted">{dayLabel(days[0])} – {dayLabel(days[6])}</span></div><div className="week-grid">{days.map(day=>{const es=recent.filter(e=>e.day===day);return <div key={day} className={day===dateKey()?'is-today':''}><span>{new Date(day+'T12:00:00').toLocaleDateString('en-GB',{weekday:'short'})}</span><strong>{new Date(day+'T12:00:00').getDate()}</strong><div className="day-dots">{pillars.map(p=><i key={p.id} title={p.name} className={es.some(e=>e.pillar===p.id)?'dot '+p.id:'dot'}/>)}</div><small>{es.length?`${es.length} recorded`:'—'}</small></div>;})}</div><div className="legend">{pillars.map(p=><span key={p.id}><i className={'dot '+p.id}/>{p.name}</span>)}</div><p className="small muted">Dots show individual pillars. Reflections across the pillars count towards your active days.</p></section><div className="section-line history-heading"><h2>Your entries</h2><span>{entries.length} saved</span></div>{entries.length===0?<div className="empty-history"><BookOpen size={32}/><h3>Your practice starts with one small step.</h3><p>Saved exercises and actions will appear here.</p><Button onClick={()=>{setTab('practice');setSelected(null);}}>Choose an exercise</Button></div>:<div className="history-list">{entries.map(e=><article key={e.id}><div className="entry-heading"><div><span className="eyebrow">{pillarName(e.pillar)} · {dayLabel(e.day)} · {e.status==='planned'?'PLANNED':e.kind==='action'?'COMPLETED':'REFLECTION'}</span><h3>{e.title}</h3></div><Button variant="ghost" aria-label={'Delete '+e.title} onClick={()=>setRemove(e.id)}><Trash2 size={17}/></Button></div>{Object.values(e.data).some(Boolean)&&<details><summary>View {e.kind==='action'?'action details':'my reflection'}</summary>{Object.entries(e.data).filter(([,v])=>v).map(([q,a])=><div className="answer" key={q}><strong>{q==='when'?'When or where':q}</strong><p>{a}</p></div>)}</details>}{e.status==='planned'&&<Button className="complete-action" variant="outline" disabled={busy} onClick={()=>complete(e)}><Check/>Mark done today</Button>}</article>)}</div>}</>}</TabsContent>
<TabsContent value="about"><div className="page-title"><p className="eyebrow">THE PEOPLE BEHIND THE FRAMEWORK</p><h1>About the <em>founders.</em></h1></div><article className="founder-profile"><div className="founder-photo"><img src="/liam-maher.jpg" alt="Liam Maher, Health Promotion Lead" width="800" height="1200" loading="lazy"/></div><div className="founder-bio"><span className="eyebrow">CO-FOUNDER</span><h2>Liam Maher</h2><p className="founder-role">Health Promotion Lead</p><p>Liam is Health Promotion Lead at John Sisk &amp; Son, supporting colleagues across Ireland, the UK and Europe. His work focuses on making health information useful in everyday life, through practical programmes, engaging conversations and opportunities for people to take action.</p><p>He holds a Master of Public Health, a BSc in Strength and Conditioning and a Level 9 qualification in Health Project Management. He brings together a background in physical health with a strong interest in emotional wellbeing, behaviour change and longevity research.</p><p>Through Emotional Health for Longevity, Liam aims to help people give connection, emotional awareness, creativity and purpose the same everyday attention they give their physical health. His approach is grounded in evidence, honest about its limitations and focused on small steps people can put into practice.</p><div className="founder-focus"><span>Public health</span><span>Practical application</span><span>Healthy longevity</span></div></div></article></TabsContent>
</main></Tabs><footer><div className="footer-brand">Emotional Health <em>for Longevity</em></div><p>For reflection and learning, not diagnosis or treatment. If you need support, speak to someone you trust, your GP, EAP or a relevant support service. If you or someone else is in immediate danger, contact local emergency services.</p><span>One small action is a good place to start.</span></footer>
<AlertDialog open={!!remove} onOpenChange={o=>!o&&setRemove(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete this entry?</AlertDialogTitle><AlertDialogDescription>This will permanently remove this action or reflection from your history.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep entry</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();deleteEntry();}}>Delete entry</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div>;
}
function Breathing(){const [running,setRunning]=useState(false),[seconds,setSeconds]=useState(0),[mode,setMode]=useState('box');const phases=mode==='box'?['Breathe in','Hold gently','Breathe out','Hold gently']:['Breathe in','Breathe out'];const total=mode==='box'?64:64;useEffect(()=>{if(!running)return;const id=setInterval(()=>setSeconds(s=>{if(s+1>=total){setRunning(false);return total;}return s+1;}),1000);return()=>clearInterval(id);},[running,total]);const phase=phases[Math.floor(seconds/4)%phases.length];return <div className="breathing-tool"><div className="breath-modes"><Button type="button" variant={mode==='box'?'default':'outline'} onClick={()=>{setMode('box');setRunning(false);setSeconds(0);}}>Box breathing</Button><Button type="button" variant={mode==='gentle'?'default':'outline'} onClick={()=>{setMode('gentle');setRunning(false);setSeconds(0);}}>Without holds</Button></div><div className={'breath-circle '+(running?'is-running':'')} style={{transform:running&&(phase==='Breathe in'||phase==='Hold gently'&&Math.floor(seconds/4)%4===1)?'scale(1.08)':'scale(1)'}}><Wind size={28}/><strong>{seconds===total?'Well done':seconds===0&&!running?'Take a moment':phase}</strong><span>{seconds===total?'Return to your usual breath':running?`${4-seconds%4} seconds`:'Breathe gently and comfortably'}</span></div><div className="breath-buttons"><Button type="button" onClick={()=>{if(seconds===total)setSeconds(0);setRunning(!running);}}>{running?<Pause/>:<Play/>}{running?'Pause':seconds===total?'Try again':seconds?'Continue':'Begin'}</Button><Button type="button" variant="ghost" onClick={()=>{setSeconds(0);setRunning(false);}}><RotateCcw/>Reset</Button></div><p className="small">{seconds} / {total} seconds · Stop if dizzy or uncomfortable.</p></div>}
